config/routes.rb
Kworkflow::Application.routes.draw do

  resources :batches do
    member do
      put :ship
      put :print
      post :ownConfirm
      post :cConfirm
    end
  end

  resources :card_types

  resources :users

  resources :cards do
    collection do
      get :import
      get :check
      post :import_excel
    end
    
    member do 
      get :receipt
    end
  end
  
  match '/misc/phone-availability' => 'miscs#phone_availability'
  match '/cards/status/:id' => 'cards#cards_by_status'
  

  
  root :to => 'application#index'

end

app/models/batch.rb
class Batch < ActiveRecord::Base
   attr_accessible :title
   validates :title, :uniqueness => true
   
   has_many :card
   
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  # GET /batches
  # GET /batches.json
  respond_to :html, :xml, :json
  def index

    batches = params[:batches]
    singles = params[:singles]
    
    status_id = params[:status_id]
    
    receiptPrinted = params[:receiptPrinted]
    receiptNptPrinted = params[:receiptNotPrinted]
    
    cardsPrinted = params[:cardsPrinted]
    cardsNotPrinted = true
    
    top = params[:top]
    
    skip = params[:skip]

    top ||= 2
    
    @batches = Batch.limit(top).offset(skip).find(:all, :include => :card,  :conditions => {:cards => {:status_id => status_id}})
    
    
    for b in @batches
      
      b[:printed]= b.card.all(:conditions => {:printed => [false, nil]}).count ==  0
      b[:receiptPrinted] = b.card.all(:conditions => {:receiptPrinted => [false, nil]}).count == 0
      
      b[:kconfirm]= b.card.all(:conditions => {:kconfirm => [false, nil]}).count ==  0
      b[:cconfirm] = b.card.all(:conditions => {:cconfirm => [false, nil]}).count == 0
      
    end
    
    res = {:batches => @batches.as_json(include: {:card => {:include=>:card_type}}), :total => Batch.count( :include => :card, :conditions => {:cards => {:status_id => status_id}})}
    
    respond_with res
    
    #render json: @batches.to_json(include: :card)
    
  end
  
  # post .batches/ship
  def ship
    
    id = params[:id]

    Card.where(:batch_id => id).update_all(:status_id => 3)
    
    respond_with Batch.find(id)

  end

  def ownConfirm
    
    id = params[:id]
    
    Card.where(:batch_id => id).update_all(:kConfirm => true)
    
    respond_with Batch.find(id)
  end
  
  def cConfirm
    id = params[:id]
    Card.where(:batch_id => id).update_all(:cConfirm => true)
    
    respond_with Batch.find(id)
  end
  
  def print
    printType = params[:t]
    
    id = params[:id]
    
    
    if printType == 1
      Card.where(:batch_id => id).update_all(:receiptPrinted => true)
    else
      Card.where(:batch_id => id).update_all(:printed => true)
    end
      
    if Card.where(:batch_id => id, :receiptPrinted => true, :printed => true).count ==  Card.where(:batch_id => id).count
      Card.where(:batch_id => id).update_all(:status_id => 3)
    end
   
    respond_with Batch.find(id)

  end
  
  # GET /batches/1
  # GET /batches/1.json
  def show
    @batch = Batch.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @batch }
    end
  end

  # GET /batches/new
  # GET /batches/new.json
  def new
    @batch = Batch.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @batch }
    end
  end

  # GET /batches/1/edit
  def edit
    @batch = Batch.find(params[:id])
  end

  # POST /batches
  # POST /batches.json
  def create
    
    
    @batch = Batch.new(params[:batch])
    
    if not params[:batch].has_key? :title
      @batch.title = Time.now.getutc
    end
    
    cards = params[:card]

    respond_to do |format|
      if @batch.save
        
        for c in cards
          Card.update c[:id], :status_id=>2, :batch_id => @batch.id
        end
        
        
        format.html { redirect_to @batch, notice: 'Batch was successfully created.' }
        format.json { render json: @batch, status: :created, location: @batch }
      else
        format.html { render action: "new" }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /batches/1
  # PUT /batches/1.json
  def update
    @batch = Batch.find(params[:id])

    respond_to do |format|
      if @batch.update_attributes(params[:batch])
        format.html { redirect_to @batch, notice: 'Batch was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /batches/1
  # DELETE /batches/1.json
  def destroy
    @batch = Batch.find(params[:id])
    @batch.destroy

    respond_to do |format|
      format.html { redirect_to batches_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/views/batches/_form.html.erb
<%= form_for(@batch) do |f| %>
  <% if @batch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@batch.errors.count, "error") %> prohibited this batch from being saved:</h2>

      <ul>
      <% @batch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/batches/edit.html.erb
<h1>Editing batch</h1>

<%= render 'form' %>

<%= link_to 'Show', @batch %> |
<%= link_to 'Back', batches_path %>

app/views/batches/index.html.erb
<h1>Listing batches</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @batches.each do |batch| %>
  <tr>
    <td><%= link_to 'Show', batch %></td>
    <td><%= link_to 'Edit', edit_batch_path(batch) %></td>
    <td><%= link_to 'Destroy', batch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Batch', new_batch_path %>

app/views/batches/new.html.erb
<h1>New batch</h1>

<%= render 'form' %>

<%= link_to 'Back', batches_path %>

app/views/batches/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_batch_path(@batch) %> |
<%= link_to 'Back', batches_path %>