config/routes.rb
Kworkflow::Application.routes.draw do

  resources :batches do
    member do
      put :ship
      put :print
      post :ownConfirm
      post :cConfirm
    end
  end

  resources :card_types

  resources :users

  resources :cards do
    collection do
      get :import
      get :check
      post :import_excel
    end
    
    member do 
      get :receipt
    end
  end
  
  match '/misc/phone-availability' => 'miscs#phone_availability'
  match '/cards/status/:id' => 'cards#cards_by_status'
  

  
  root :to => 'application#index'

end

app/models/card.rb
class Card < ActiveRecord::Base
 
 attr_accessible :nameOnCard, :number,:user_id, :batch_id, :type_id, :expirationDate, :subscriptionDate, :expired, :sanityChecked, :called, :status_id, :locked
 
 belongs_to :user
 belongs_to :batch
 belongs_to :card_type, :foreign_key => "type_id"
 belongs_to :card_issue, :foreign_key => "issue_id"
 belongs_to :card_status, :foreign_key => "status_id"
 
 validates :number, :length => { 
    :is => 16,
    :too_long  => "must be %{count} digits",
    :too_short  => "must be %{count} digits"
    
    },
    :presence => true,
    :uniqueness => true
    
    
    def save
      
      if self.number == nil || self.number.empty?
        #assign a uniquenumber
        
        self.number = "UNIQUE_NUMBER"
        
      end

      super
      
      
    end
 
end

app/models/card_type.rb
class CardType < ActiveRecord::Base
  attr_accessible :title, :expirationMonths, :isDefault, :premium
  
  has_many :card, :foreign_key => "type_id"
  
  
  def toString
    "#{title} (#{expirationMonths} months)"
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  # GET /cards
  # GET /cards.json
  respond_to :html, :xml, :json
  
  before_filter :set_globals
  
  def index
    
    
    
    #puts "RENDERING INDEXXXXXXXXXXX"
    #@cards = Card.all
    #respond_to do |format|
    #  format.html
    #  format.json { render :json => @cards }
    #end
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    @card = Card.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @card }
    end
  end

  # GET /cards/new
  # GET /cards/new.json
  def new
    @card = Card.new
    #@user = User.new
    @user = User.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @card }
    end
  end

  # GET /cards/1/edit
  def edit
    
    @card = Card.find(params[:id])
    @user = User.find(@card.user_id)
    
    render :layout => false
    
  end

  def cards_by_status
    
    skip = params[:skip]
    top = params[:top]
    #Card.include_root_in_json = true
    #@cards = Card.limit(top).offset(skip).where(["status_id = ?", params[:id]])
    
    @cards= Card.limit(top).offset(skip).find(:all,  :conditions => {:status_id => 1})
    
    res = {:cards => @cards.as_json(include: :card_type), :total => Card.count(:conditions => {:status_id => 1})}
    
    respond_with res
    '''respond_to do |format|

      format.html
      format.json {render :json => @cards}
  end'''
  end
  
  def import
    
  end
  
  def new_success
    
  end
  
  # POST
  
  def lock
    id = params[:id]

    @card = Card.find id
    
    
     render :json => @card
    
    
  end
    
  # POST
  def import_excel
    

    if params.has_key? :fileid
      
      import = Import.where(["name = ? AND isValid = ? AND deleted = ?", params[:fileid], true, false]).first
      
      
      
    else
       import = Import.new
       import.save(params[:sheet].tempfile.path, params[:sheet].original_filename)
    end

    begin

      if import.id
        file = import.getFilePath
        @fileid = File.basename(file).split(File.extname(file)).first
        s = Roo::Excelx.new(file)
      
        s.default_sheet = s.sheets[4]
        
        @data = []

        4.upto s.last_row do |row|
          
          if s.cell(row, 'B').blank?
            break
          end
          
          @data.push({
            :id => s.cell(row, 'A'),
            :fullName => s.cell(row, 'B'),
            :firstName => s.cell(row, 'C'),
            :lastName => s.cell(row, 'D'),
            :mobile => s.cell(row, 'E'),
            :email => s.cell(row, 'F'),
            :dob => s.cell(row, 'G'),
            :type => s.cell(row, 'H'),
            :amount => s.cell(row, 'I')
            
          })

        import.setValid(true)
        end

      else
        raise TypeError
      end
      

    rescue TypeError
      @error = "Invalid EXCEL SHEET"
      #redirect_to :action => :import
      render :import
    ensure
      
    end
    
  end
  
  
  
  def check
    
    @cards = Card.where(["status_id = ?", 1])
    
  end
  
  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(params[:card])
    
    if not params[:card].has_key? :number
      r = Random.new
      @card.number = r.rand(1111111111111111...9999999999999999).to_s #@@TODO replace with correct number

    end
    
    if not params[:card].has_key? :status_id
      @card.status_id = 1
    end
    
    #if not params[:card].has_key? :
    
    if params[:card].has_key? :user_id
      @user = User.find(params[:card][:user_id])
    else
      @user = User.where(:email=> params[:user][:email]).first || User.new(params[:user])
    end
    
   
    
    unless @user.id
      @user.save
    end

    @card.user_id = @user.id

    respond_to do |format|
      if @user.id && @card.save
        #format.html { redirect_to @card, :notice => 'Card was successfully created.' }
        
        
        
        format.html { render :action => "index"}
        format.json { render :json => @card, :status => :created, :location => @card }
        
        
        
      else
        format.html { render :action => "new" }
        format.json { render :json => @card.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  
  def create_async
    @card = Card.new(params[:card])
    @user = User.where(:email=> params[:user][:email]).first || User.new(params[:user])
    
    unless @user.id
      @user.save
    end

    @card.user_id = @user.id

    respond_to do |format|
      if @user.id && @card.save
        #format.html { redirect_to @card, :notice => 'Card was successfully created.' }
        #format.json { render :json => @card, :status => :created, :location => @card }
        
        render :action => "new_success"
        
      else
        format.html { render :action => "new" }
        format.json { render :json => @card.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cards/1
  # PUT /cards/1.json
  def update
    @card = Card.find(params[:id])
  
    respond_to do |format|
      if @card.update_attributes(params[:card])
        format.html { redirect_to @card, :notice => 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @card.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card = Card.find(params[:id])
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end
  
  def receipt
    @card = Card.find params[:id]
    
    render :layout => false
    
  end
  
  protected
  
    def set_globals
      @identifier="cards"
    end
    

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_base.html.erb
<% content_for :submenu do %>
	<%= render :partial => 'partials/submenu',  :locals => {:items => 
		
		
		{"Flow" => [
			{
				:id => "check",
				:href => "/cards#check",
				:title=>"list cards",
				:text=>"Pending Check"
			},
			
			{
				:id => "production",
				:href => "/cards#production",
				:title=>"list cards",
				:text=>"In production"
			},
			
			{
				:id => "shipments",
				:href => "/cards#shipments",
				:title=>"list cards",
				:text=>"Shipments"
			}
		],

		"Add" => [

			{
				:id => "add",
				:href => "/cards/new",
				:title =>"Add card",
				:text =>"Add Card"
			},
			
			{
				:id => "import",
				:href => "/cards/import",
				:title =>"Upload cards",
				:text =>"Upload Excel Sheet"
			}
			
		]
		
		
		
		
		},
		
		
		:current => current } %>
<% end %>

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/check.html.erb
<%= render :partial => 'cards/base', :locals => { :current => "check"} %>
<% content_for :title do %>
  Cards
<% end %>

<% content_for :subtitle do %>
  Listing cards
<% end %>

<div id="cards_section_1">
	
</div>

<div id="cards_section_2">
	
</div>

<!--table class="table table-hover table-striped">
	<thead>
		<tr class="info">
			<th><input type="checkbox" class="selectAll">
			</th><th>#</th>
			<th>Name on card</th>
			<th>Card number</th>
			<th>Issue date</th>
			<th>Expiration date</th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	
	<tbody>
		
		
		<% @cards.each do |card| %>
		
		<tr>
		  <td>
			<input type="checkbox" class="selectCard" id="0000">
		  </td>
	      <td><%= card.id %></td>
		  <td><%= card.nameOnCard %></td>
	      <td><%= card.number %> </td>
		  <td><%= card.created_at %></td>
		  <td><%= card.expirationDate %></td>
		  <td>
			<a href="#">
				<span src="" class="icon-edit">&nbsp;</span>
			</a></td>
	    </tr>
		
		
		
		<% end %>

	</tbody>
</table-->

<script type="text/javascript">
	//window.queuedUrl = "cards/check"
</script>

app/views/cards/edit.html.erb
<tr>
	<td colspan="9">
		<%= form_for @card, :url => {:action => "create"} do |card_form| %>
			
			<div class="row-fluid">
	  <fieldset class="span6">
	    <legend>User information</legend>

	    <%= fields_for @user do |user_fields| %>
	    	
	    	<% unless user_fields.error_messages.length == 0%>
	    	<div class="alert alert-error">
	    	<%= user_fields.error_messages %>
	    	</div>
	    	<% end %>
	    	<label>First name</label>
		    
		    <%= user_fields.text_field :firstName, :placeholder=>"First Name" %>
		    
		    <label>Last name</label>
	    	<%= user_fields.text_field :lastName, :placeholder=>"Last Name" %>
		    
		    <label>Gender</label>
		    <select>
		    	<option>Male</option>
		    	<option>Female</option>
		   	</select>
		    
		    <label>University</label>
		    <input type="text" placeholder="University">

		    <label>Email</label>
	    	<%= user_fields.text_field :email, :placeholder=>"Email" %>
		    
		 <% end %>
	  </fieldset>

	  
	  <fieldset class="span6">
	    <legend>Card information</legend>
	    
	    <% unless card_form.error_messages.length == 0%>
    	<div class="alert alert-error">
    	<%= card_form.error_messages %>
    	</div>
    	<% end %>
	    <label>Name on card</label>
	    <%= card_form.text_field :nameOnCard, :placeholder=>"Name on Card" %>
	    <span class="help-block">Name to printed on the card must be 23 characters only!</span>

	    <label>Card type</label>
	    <%# collection_select(:card, :type_id, Card::CardTypes) %>
	    <%= card_form.collection_select :type_id, CardType.all.sort.reverse, :id, :toString %>
	    
	    <span class="help-block">Expiration months are beside each card type in months</span>
	    
	    
	    <label>Card issue</label>
	    <select>
	    	<option>Card of Nov 2012</option>
	   	</select>
	    <span class="help-block">Issue date is beside each issue title in the combo-box items</span>
	    
	    
	    <label>Card number</label>
	    <%= card_form.text_field :number, :placeholder=>"0000000000000000" %>

	    
	  </fieldset>
 
  </div>
  

  <div class="form-actions">
  	<button type="submit" class="btn btn-success">Submit</button>
  	
  	<a href="#" class="btn btn-danger btn">Cancel</a>
  </div>
  
  
		<% end %>
	</td>
</tr>

app/views/cards/import.html.erb
<%= render :partial => 'cards/base', :locals => { :current => "import" } %>
<%# render 'form' %>

<% content_for :title do %>
  Cards
<% end %>


<% content_for :subtitle do %>
 	Import Excel Sheet
<% end %>



<!--form>
  <fieldset>
    <legend>User information</legend>
    <label>First name</label>
    <input type="text" placeholder="Type something…">
    <span class="help-block">Example block-level help text here.</span>
    <label class="checkbox">
      <input type="checkbox"> Check me out
    </label>
    <button type="submit" class="btn">Submit</button>
  </fieldset>
</form-->



<%= form_tag({:action => :import_excel}, :multipart => true) do %>
	
  <div class="row-fluid">
	  <fieldset class="span12">
	    <legend>Excel Sheet Selection</legend>
	    
	    <label>Excel Sheet file</label>
	     <%= file_field_tag 'sheet' %>
	    
	  
	    
	  </fieldset>

  </div>
  
  
  <div class="form-actions">
  	<button type="submit" class="btn btn-success">Import</button>
  	
  	<a href="<%=cards_path%>" class="btn btn-danger btn">Cancel</a>
  </div>
  
  
  
<% end %>

app/views/cards/import_excel.html.erb
<%= render :partial => 'cards/base', :locals => { :current => "import" } %>
<%# render 'form' %>

<% content_for :title do %>
  Cards
<% end %>


<% content_for :subtitle do %>
 	Confirm uploaded data
<% end %>


<table class="table table-hover table-striped">
	<thead>
		<tr class="info">
			<th>ID</th>
			<th>Fullname</th>
			<th>First name</th>
			<th>Last name</th>
			<th>Mobile</th>
			<th>Email</th>
			<th>Date of Birth</th>
			<th>Type</th>
			<th>Amount</th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	
	<tbody>
		
		<% @data.each do |item| %>
		<tr>
		  <td>
			<%= item[:id]%>
		  </td>
	      <td><%= item[:fullName]%></td>
		  <td><%= item[:firstName]%></td>
	      <td><%= item[:lastName]%></td>
		  <td><%= item[:mobile]%></td>
		  <td><%= item[:email]%></td>
		  <td><%= item[:dob]%></td>
		  <td><%= item[:type]%></td>
		  <td><%= item[:amount]%></td>
		  <td class="status_indicator_norm"><span class="icon-ok"></span> <img class="spinner" src="/assets/spinner.gif" /></td>
		  
	    </tr>
		
		<% end %>
	
	</tbody>
</table>
<script>
$(function(){
	
	$(".confirm_excel").click(function(){
	
	
	trs = $("tr")
	
	for(var i =0; i<trs.length; i++) {
		
		
	}
	
	$("tr").each(function(){
		
		
		$(this).find("td:last").removeClass("status_indicator_norm").addClass("status_indicator_progress");
		
		
		card = new Kworkflow.Models.Card();
		
		card.set("nameOnCard", $($(this).find("td")[1]).text())
		card.set("type_id", 1)
		//card.set("number", "00000000000000")
		
		card.User = new Kworkflow.Models.User()
		
		card.User.set("email", $($(this).find("td")[5]).text())
		card.User.set("firstName", $($(this).find("td")[2]).text())
		card.User.set("lastName", $($(this).find("td")[3]).text());
		
		
		(function(c, tr) {
		
			card.User.save({}, {success: function(u) {
				
				c.set("user_id", u.get("id"))
				
				c.save()
				
				$(tr).find("td:last").removeClass("status_indicator_progress").addClass("status_indicator_success");
				
			
			}
		
		})})(card, this);
		
		
		
		
		
		//card.save()
		
	});
});
})


</script>

<%# form_tag({:action => :import_excel}, :multipart => true) do %>
  
  <div class="form-actions">
  	
  	<input type="hidden" name="fileid" value="<%=@fileid%>">
  	<button type="submit" class="btn btn-success btn confirm_excel">Confirm</button>
  	
  	<a href="<%=:back%>" class="btn btn-danger btn">Cancel</a>
  </div>
  
<%# end %>

app/views/cards/index.html.erb
<%= render :partial => 'cards/base', :locals => { :current => "index"} %>
<% content_for :title do %>
<% end %>

<% content_for :subtitle do %>
 
<% end %>

<div id="cards_root">
</div>


<script>
	window.Router = Kworkflow.Routers.Cards
</script>

app/views/cards/new.html.erb
<%= render :partial => 'cards/base', :locals => { :current => "add" } %>
<%# render 'form' %>






<% content_for :title do %>
  Cards
<% end %>


<% content_for :subtitle do %>
  New card
<% end %>



<!--form>
  <fieldset>
    <legend>User information</legend>
    <label>First name</label>
    <input type="text" placeholder="Type something…">
    <span class="help-block">Example block-level help text here.</span>
    <label class="checkbox">
      <input type="checkbox"> Check me out
    </label>
    <button type="submit" class="btn">Submit</button>
  </fieldset>
</form-->



<%= form_for @card, :url => {:action => "create"} do |card_form| %>
	
  <div class="row-fluid">
	  <fieldset class="span6">
	    <legend>User information</legend>

	    <%= fields_for @user do |user_fields| %>
	    	
	    	<% unless user_fields.error_messages.length == 0%>
	    	<div class="alert alert-error">
	    	<%= user_fields.error_messages %>
	    	</div>
	    	<% end %>
	    	<label>First name</label>
		    
		    <%= user_fields.text_field :firstName, :placeholder=>"First Name" %>
		    
		    <label>Last name</label>
	    	<%= user_fields.text_field :lastName, :placeholder=>"Last Name" %>
		    
		    <label>Gender</label>
		    <select>
		    	<option>Male</option>
		    	<option>Female</option>
		   	</select>
		    
		    <label>University</label>
		    <input type="text" placeholder="University">

		    <label>Email</label>
	    	<%= user_fields.text_field :email, :placeholder=>"Email" %>
		    
		 <% end %>
	  </fieldset>

	  
	  <fieldset class="span6">
	    <legend>Card information</legend>
	    
	    <% unless card_form.error_messages.length == 0%>
    	<div class="alert alert-error">
    	<%= card_form.error_messages %>
    	</div>
    	<% end %>
	    <label>Name on card</label>
	    <%= card_form.text_field :nameOnCard, :placeholder=>"Name on Card" %>
	    <span class="help-block">Name to printed on the card must be 23 characters only!</span>

	    <label>Card type</label>
	    <%# collection_select(:card, :type_id, Card::CardTypes) %>
	    <%= card_form.collection_select :type_id, CardType.all.sort.reverse, :id, :toString %>
	    
	    <span class="help-block">Expiration months are beside each card type in months</span>
	    
	    
	    <label>Card issue</label>
	    <%= card_form.collection_select :issue_id, CardIssue.all.sort.reverse, :id, :toString %>
	    <span class="help-block">Issue date is beside each issue title in the combo-box items</span>
	    
	    
	    <label>Card number</label>
	    <%= card_form.text_field :number, :placeholder=>"0000000000000000" %>
	     
	    
	    
	  </fieldset>
 
  </div>
  
  <div class="row-fluid">
  	<fieldset class="span12">
  		
  		<legend>Dev options</legend>
  		
  		<label>Next Stage</label>
  		
  		<%= card_form.collection_select :status_id, CardStatus.all, :id, :title %>
  		
  		<label class="checkbox">
  		<%= card_form.check_box :called %> Called
  		</label>
  		
  		<label class="checkbox">
  		<%= card_form.check_box :sanityChecked %> Sanity Checked
  		</label>
  		
  	</fieldset>
  </div>
  
  
  <div class="form-actions">
  	<button type="submit" class="btn btn-success">Submit</button>
  	
  	<a href="<%=cards_path%>" class="btn btn-danger btn">Cancel</a>
  </div>
  
  
  
<% end %>

app/views/cards/new_success.html.erb
<%= render :partial => 'cards/base', :locals => { :current => "add" } %>
<%# render 'form' %>

<% content_for :title do %>
  Cards
<% end %>


<% content_for :subtitle do %>
  New card
<% end %>


	Success

app/views/cards/receipt.html.erb
<!DOCTYPE html>
<html>
  <head>
    <style>
    body {
        height: 842px;
        width: 1120px;
        /* to centre page on screen*/
        margin-left: auto;
        margin-right: auto;
    }
    </style>
  <head>
  <body>
  	h
  </body>
</html>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>